title:
  en: Perro's Blog  ğŸ¶
  es: Blog del Perro  ğŸ¶
email: david.ojeda.lopez@gmail.com
description:
  en: Software, motivation, life tricks, and some random stuff!
  es: Software, motivaciÃ³n, trucos de vida y cosas aleatorias
name: David Ojeda LÃ³pez
theme: jekyll-theme-slate
permalink: /blog/:year/:month/:day/:title
github_username: davidojedalopez
twitter_username: DavidOjedaL
