title:
  en: Perro's Blog  ğŸ¶
  es: Blog del Perro  ğŸ¶
email: david.ojeda.lopez@gmail.com
description:
  en: Software tutorials, tricks, opinions, and more!
  es: Â¡Tutoriales, trucos e ideas de software!
name: David Ojeda LÃ³pez
theme: jekyll-theme-slate
permalink: /blog/:year/:month/:day/:title
github_username: davidojedalopez
twitter_username: DavidOjedaL
future: true
plugins:
  - jekyll-gist
  - jekyll-sitemap